#!/usr/bin/env python3
"""Generate the master-data seed migration (M-123) for the Production Daily
Report feature from the client's Excel workbook.

Reads the four "dictionary" sheets of
  docs/2026 Daily Report Forming Production.xlsx
and emits idempotent INSERT statements into
  supabase/migrations/20260610000002_prod_daily_report_seed.sql

Sources -> target tables:
  RAW DATA      -> prod_product_master   (+ Other INF codes not already present)
  name item     -> prod_operator
  Machine DATA  -> prod_machine (col C) and prod_downtime_reason (col A)

This is a one-off generator, NOT part of the app build. Re-run it only when the
client ships an updated workbook. Requires openpyxl (pip install openpyxl).
"""
import os
import re
import openpyxl

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)                       # eee-main/
XLSX = os.path.normpath(os.path.join(REPO, '..', 'docs',
                                     '2026 Daily Report Forming Production.xlsx'))
OUT = os.path.join(REPO, 'supabase', 'migrations',
                   '20260610000002_prod_daily_report_seed.sql')


def q(v):
    """SQL string literal (or NULL) from a Python value."""
    if v is None:
        return 'NULL'
    s = str(v).strip()
    if s == '':
        return 'NULL'
    return "'" + s.replace("'", "''") + "'"


def num(v):
    """SQL numeric literal (or NULL)."""
    if v is None or v == '':
        return 'NULL'
    try:
        return repr(float(v))
    except (TypeError, ValueError):
        return 'NULL'


def slug(s):
    m = re.match(r'[A-Za-z0-9 /&\-]+', str(s))
    base = (m.group(0) if m else 'reason').strip().lower()
    return re.sub(r'[^a-z0-9]+', '_', base).strip('_') or 'reason'


def main():
    wb = openpyxl.load_workbook(XLSX, data_only=True, read_only=True)

    # ── prod_product_master ← RAW DATA (cols: item,desc,sz,proc,oz,lbs/hr,
    #    pcs(lbs)/hr,runner,bone,note). Dedupe by item_number keeping the FIRST
    #    occurrence — Excel VLOOKUP returns the first match, so the computed
    #    columns only stay 1:1 with the workbook if we mirror that. ──
    ws = wb['RAW DATA']
    products = {}
    for r in ws.iter_rows(min_row=2, values_only=True):
        if r[0] in (None, ''):
            continue
        item = str(r[0]).strip()
        if item in products:
            continue
        products[item] = {
            'item_number': item,
            'description': (r[1].rstrip() if isinstance(r[1], str) else r[1]),
            'size': r[2], 'process': r[3], 'oz_per_piece': r[4],
            'lbs_per_hr': r[5], 'pcs_lbs_per_hour': r[6],
            'runner_avg': r[7], 'bone_avg': r[8], 'note': r[9],
        }

    # Merge "Other INF" activity/special codes not already in RAW DATA.
    ws = wb['Other INF']
    for r in ws.iter_rows(min_row=1, values_only=True):
        if r[0] in (None, ''):
            continue
        code = str(r[0]).strip()
        if code in products:
            continue
        products[code] = {
            'item_number': code, 'description': r[1],
            'size': None, 'process': None, 'oz_per_piece': None,
            'lbs_per_hr': None, 'pcs_lbs_per_hour': None,
            'runner_avg': None, 'bone_avg': None, 'note': 'Other INF',
        }

    def is_activity(p):
        rate = p['pcs_lbs_per_hour'] or 0
        bone = p['bone_avg'] or 0
        return (not rate) and (not bone)

    # ── prod_machine ← Machine DATA col C ; prod_downtime_reason ← col A ──
    ws = wb['Machine DATA']
    rows = list(ws.iter_rows(values_only=True))
    machines, mseen = [], set()
    reasons, rseen = [], set()
    for r in rows[1:]:
        code = r[2] if len(r) > 2 else None
        if code and str(code).strip() not in mseen:
            c = str(code).strip()
            mseen.add(c)
            kind = ('inj' if c.lower().startswith('inj')
                    else 'ext' if c.lower().startswith('ext') else 'other')
            machines.append((c, kind))
        rs = r[0] if len(r) > 0 else None
        if rs and str(rs).strip() not in rseen:
            label = str(rs).strip()
            rseen.add(label)
            reasons.append((slug(label), label))

    # ── prod_operator ← name item (badge_no -> name; only named rows) ──
    ws = wb['name item']
    operators = []
    for r in ws.iter_rows(min_row=2, values_only=True):
        if r[0] in (None, '') or r[1] in (None, ''):
            continue
        try:
            badge = int(r[0])
        except (TypeError, ValueError):
            continue
        operators.append((badge, str(r[1]).strip()))

    # ── emit SQL ──
    L = []
    L.append("-- Migration M-123: Production Daily Report master-data seed")
    L.append("--")
    L.append("-- Auto-generated by scripts/gen_prod_seed.py from")
    L.append("--   docs/2026 Daily Report Forming Production.xlsx")
    L.append("-- Seeds the four dictionary tables that drive the Daily Report's")
    L.append("-- dropdowns and computed columns. Idempotent (ON CONFLICT DO NOTHING).")
    L.append("-- Re-generate via the script when the client ships a new workbook.")
    L.append("--")
    L.append("-- Depends on: M-122 (prod_* schema). Affects: docs/database/03..., "
             "docs/modules/12_production-daily-report.md.")
    L.append("")

    # machines
    L.append(f"-- Machines ({len(machines)})")
    L.append("INSERT INTO prod_machine (code, kind, sort_order, created_by) VALUES")
    vals = [f"  ({q(c)}, {q(k)}, {i}, 'system:M-123')"
            for i, (c, k) in enumerate(machines)]
    L.append(",\n".join(vals))
    L.append("ON CONFLICT (code) DO NOTHING;\n")

    # downtime reasons
    L.append(f"-- Downtime reasons ({len(reasons)})")
    L.append("INSERT INTO prod_downtime_reason (code, label, sort_order, created_by) VALUES")
    vals = [f"  ({q(c)}, {q(lbl)}, {i}, 'system:M-123')"
            for i, (c, lbl) in enumerate(reasons)]
    L.append(",\n".join(vals))
    L.append("ON CONFLICT (code) DO NOTHING;\n")

    # operators
    L.append(f"-- Operators ({len(operators)})")
    L.append("INSERT INTO prod_operator (badge_no, name, created_by) VALUES")
    vals = [f"  ({b}, {q(n)}, 'system:M-123')" for b, n in operators]
    L.append(",\n".join(vals))
    L.append("ON CONFLICT (badge_no) DO NOTHING;\n")

    # products
    plist = list(products.values())
    L.append(f"-- Products ({len(plist)})")
    L.append("INSERT INTO prod_product_master (item_number, description, size, process,")
    L.append("  oz_per_piece, lbs_per_hr, pcs_lbs_per_hour, runner_avg, bone_avg,")
    L.append("  is_activity, note, created_by) VALUES")
    vals = []
    for p in plist:
        vals.append(
            f"  ({q(p['item_number'])}, {q(p['description'])}, {q(p['size'])}, "
            f"{q(p['process'])}, {num(p['oz_per_piece'])}, {num(p['lbs_per_hr'])}, "
            f"{num(p['pcs_lbs_per_hour'])}, {num(p['runner_avg'])}, {num(p['bone_avg'])}, "
            f"{'true' if is_activity(p) else 'false'}, {q(p['note'])}, 'system:M-123')")
    L.append(",\n".join(vals))
    L.append("ON CONFLICT (item_number) DO NOTHING;")
    L.append("")

    with open(OUT, 'w') as f:
        f.write("\n".join(L))

    print(f"wrote {OUT}")
    print(f"  machines={len(machines)} reasons={len(reasons)} "
          f"operators={len(operators)} products={len(plist)} "
          f"(activities={sum(1 for p in plist if is_activity(p))})")


if __name__ == '__main__':
    main()
